import { DEPTS } from '../constants/depts'
import { SEV_COLORS } from '../constants/colors'

export function exportBrief(sit,dept,interp){
  const deptInfo=DEPTS.find(d=>d.key===dept);
  const deptLabel=deptInfo?.label||'All Departments';
  const html=`<!DOCTYPE html><html><head><meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
body{font-family:'DM Sans',sans-serif;font-size:12px;color:#111318;max-width:760px;margin:40px auto;padding:0 48px;line-height:1.5}
.ph{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #111318;padding-bottom:16px;margin-bottom:24px}
.logo{font-family:'IBM Plex Mono',monospace;font-size:11px;letter-spacing:.12em;color:#111318}
.logo-sub{font-size:9px;color:#9CA3AF;letter-spacing:.06em}
.meta{font-family:'IBM Plex Mono',monospace;font-size:9px;color:#6B7280;text-align:right;line-height:1.8}
h1{font-family:'Playfair Display',serif;font-size:24px;font-weight:500;margin:0 0 6px;line-height:1.2}
h2{font-family:'IBM Plex Mono',monospace;font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#6B7280;margin:20px 0 8px;border-top:1px solid #E2E4E8;padding-top:10px}
p{color:#374151;margin:0 0 8px;line-height:1.65}
.headline{font-size:14px;font-weight:600;color:#111318;margin:0 0 10px}
.action{padding:4px 0;display:flex;gap:8px;font-size:11px;color:#374151;align-items:flex-start}
.action-urgent{color:#B22222;font-weight:500}
.action::before{content:"→";color:#9CA3AF;flex-shrink:0}
.action-urgent::before{color:#B22222}
.utag{font-family:'IBM Plex Mono',monospace;font-size:8px;background:#FEF2F2;color:#B22222;border:1px solid #FECACA;padding:1px 4px;border-radius:2px;margin-right:4px}
.tags{display:flex;gap:4px;flex-wrap:wrap;margin:6px 0}
.tag{font-family:'IBM Plex Mono',monospace;font-size:9px;padding:2px 6px;background:#F3F4F6;border:1px solid #E2E4E8;border-radius:2px;color:#6B7280}
.sev{font-family:'IBM Plex Mono',monospace;font-size:10px;letter-spacing:.06em;font-weight:500}
@media print{body{margin:0;padding:24px}}
</style></head><body>
<div class="ph">
  <div><div class="logo">AURA</div><div class="logo-sub">INSURANCE INTELLIGENCE · DOHA</div></div>
  <div class="meta"><div>${deptLabel.toUpperCase()}</div><div>10 March 2026</div><div>Ref: ${sit.id.toUpperCase()}</div></div>
</div>
<span class="sev" style="color:${SEV_COLORS[sit.severity]}">${sit.severity}</span>${sit.isLive?' <span style="background:#1E3A5F;color:#fff;font-family:IBM Plex Mono,monospace;font-size:9px;padding:2px 6px;border-radius:2px;letter-spacing:.06em">LIVE</span>':''}
<h1>${sit.title}</h1>
<p style="color:#6B7280;font-size:13px;margin-bottom:8px">${sit.subtitle}</p>
<div class="tags">${sit.category.map(c=>`<span class="tag">${c}</span>`).join('')}</div>
<h2>Situation Summary</h2><p>${sit.summary}</p>
${interp?`<h2>${deptLabel} Brief</h2>
<div class="headline">${interp.headline}</div>
<p>${interp.detail}</p>
${interp.affectedLines?`<h2>Affected Lines</h2><div class="tags">${interp.affectedLines.map(l=>`<span class="tag">${l}</span>`).join('')}</div>`:''}
${interp.actions?`<h2>Actions</h2>${interp.actions.map((a,i)=>`<div class="action ${i<2?'action-urgent':''}">${i<2?'<span class="utag">URGENT</span>':''} ${a}</div>`).join('')}`:''}
`:''}
<div style="margin-top:40px;padding-top:12px;border-top:1px solid #E2E4E8;font-family:'IBM Plex Mono',monospace;font-size:9px;color:#9CA3AF">
Generated by AURA Insurance Intelligence · 10 March 2026 · Confidence: ${sit.confidence}%</div>
</body></html>`;
  const w=window.open('','_blank');
  if(!w){alert('Allow pop-ups to export brief');return;}
  w.document.write(html);w.document.close();
  setTimeout(()=>w.print(),500);
}
